### ISSUE TITLE
vivado_video

### ISSUE THREAD

**Issue by sharmilakotra** [JoshuaEbenezer/vivado_hls#1]
hi actually the code looks good and am very happy to got the code for video read and write but its is not working in 2017.4 vivado hls in windows and showing error below

Starting C simulation ...
C:/Xilinx/Vivado/2017.4/bin/vivado_hls.bat C:/projects/video_new/solution1/csim.tcl
INFO: [HLS 200-10] Running 'C:/Xilinx/Vivado/2017.4/bin/unwrapped/win64.o/vivado_hls.exe'
INFO: [HLS 200-10] For user 'HP' on host 'desktop-sab6oh4' (Windows NT_amd64 version 6.2) on Thu Jan 03 09:32:38 +0530 2019
INFO: [HLS 200-10] In directory 'C:/projects'
INFO: [HLS 200-10] Opening project 'C:/projects/video_new'.
INFO: [HLS 200-10] Opening solution 'C:/projects/video_new/solution1'.
INFO: [SYN 201-201] Setting up clock 'default' with a period of 10ns.
INFO: [HLS 200-10] Setting target device to 'xc7z030fbg484-2'
INFO: [SIM 211-2] *************** CSIM start ***************
INFO: [SIM 211-4] CSIM will launch GCC as the compiler.
make: `csim.exe' is up to date.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<unsigned char>.5' is read while empty, which may result in RTL simulation hanging.

**Comment by JoshuaEbenezer** [comment]
The code in this repo is not actually complete...they are just demos. The warning you are getting is because output has not been written to the HLS Mat that you are accessing. Make sure that all the Mat objects that you declare in your code are being used (i.e. either read from or written to). The warning should disappear after that.
